artifacts_root: artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: "https://drive.usercontent.google.com/download?id=14TKV_GemwhVZIzqD3ETLJ7mBafyu9fzO&export=download&authuser=1&confirm=t&uuid=8dd5c2cd-8930-42b4-93d2-28e45e8ed2c2&at=AN8xHopiAbOGKBiCgpBpVnyV6Ufq%3A1751434119045"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5